### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [yuusoyeon/C202309#3]
### 없는 파일
- challenge/week6/studentGrade.c
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week3/do-while_even
    - Error: expected '}' [line 16]
         - 중괄호를 맞춰주세요.

**Comment by yuusoyeon** [comment]
해결했습니다.
